kind: pipeline
type: docker
name: default

workspace:
  path: /drone/src

steps:
- name: dingtalk
  image: lddsb/drone-dingtalk-message
  settings:
    token: e6a8fb84948590317c8220f3c8408d9b301b34ceb766c667613f3843688b23d8
    type: markdown
    secret: G
    sha_link: https://git.yulei.icu/yulei/openclash-rule