kind: pipeline
type: docker
name: default

workspace:
  path: /drone/src

branches: dev

steps:
- name: dingtalk
  image: lddsb/drone-dingtalk-message
  settings:
    token: e6a8fb84948590317c8220f3c8408d9b301b34ceb766c667613f3843688b23d8
    type: markdown
    secret: G
    tpl : https://git.yulei.icu/yulei/openclash-rule/raw/branch/dev/markdown.tpl
    sha_link: https://git.yulei.icu/yulei/openclash-rule

- name: send
  image: plugins/webhook
  settings:
    urls: http://192.168.31.20:8066/prod-webhook?secret=5e4EymRdf0SsFT9O
    template:
          {
              "accept_title": "open-clash规则更新完成",
              "accept_desp": "open-clash规则更新完成",
          }




# - name: git-push
#   image: appleboy/drone-git-push
#   settings:
#     branch: dev
#     remote: git@gitee.com:Colombeblanche/openclash-rule.git
#     ssh_key:
#       from_secret: gitee-ssh-key
#     local_branch: dev
#     force: true
#     commit: true
#     author_name: yueli
#     author_email: yulei5024@gmail.com